pkrog/biodb

R/BiodbConn.R, R/BiodbDbInfo.R, R/BiodbDbsInfo.R, R/ChebiConn.R, R/ChemspiderConn.R, R/ExpasyEnzymeConn.R, R/HmdbMetaboliteConn.R, R/KeggConn.R, R/LipidmapsStructureConn.R, R/MassCsvFileConn.R, R/MassbankConn.R, R/MirbaseMatureConn.R, R/NcbiCcdsConn.R, R/NcbiGeneConn.R, R/NcbiPubchemCompConn.R, R/NcbiPubchemSubstConn.R, R/PeakforestConn.R, R/RemotedbConn.R, R/UniprotConn.R, R/biodb-common.R
=> Move content-type into DbInfo class.

R/BiodbEntry.R
=> Automatically set the database id field from the accession field.

R/BiodbEntry.R, R/BiodbEntryField.R, R/BiodbEntryFields.R, R/MassbankEntry.R, tests/res/entry-peakforest.mass-1000.json, tests/res/entry-peakforest.mass-75.json
Now ms.mode field values are controlled.
=> Implement enumerated type.

R/BiodbDbsInfo.R, R/ChebiConn.R, R/ChemspiderConn.R, R/ExpasyEnzymeConn.R, R/HmdbMetabolitesConn.R, R/KeggCompoundConn.R, R/KeggConn.R, R/LipidmapsStructureConn.R, R/MassbankConn.R, R/MirbaseMatureConn.R, R/NcbiCcdsConn.R, R/NcbiGeneConn.R, R/NcbiPubchemConn.R, R/PeakforestCompoundConn.R, R/PeakforestMassConn.R, R/UniprotConn.R, tests/testthat/db-generic-tests.R
=> Implement getEntryImageUrl() for all databases.

R/MassdbConn.R
Implement RT tolerance in exponent.
=> Implement RT tol exp.

tests/res/entry-hmdb.metabolites-HMDB0000001.json, tests/res/offline-cache/hmdb.metabolites-HMDB0000001.xml
=> Update HMDB test ref files.

R/BiodbEntryFields.R, R/BiodbFactory.R, R/ChebiConn.R, R/ChemspiderConn.R, R/CompounddbConn.R, R/ExpasyEnzymeConn.R, R/HmdbMetabolitesConn.R, R/KeggCompoundConn.R, R/LipidmapsStructureConn.R, R/MirbaseMatureConn.R, R/NcbiGeneConn.R, R/NcbiPubchemCompConn.R, R/PeakforestCompoundConn.R, R/UniprotConn.R, tests/testthat/db-compound-tests.R
=> Check mass.field in searchCompound().

README.md, tests/testthat/db-peakforest-tests.R
=> Correct PeakForest Mass RT test.

R/BiodbConn.R, R/BiodbConnBase.R, R/BiodbDbsInfo.R, R/BiodbFactory.R, R/BiodbRequestScheduler.R, R/MassbankConn.R
Solves #246.
* Implement single URL field as a list of keys & values inside `BiodbConnBase`, as suggested in #246.
* Load Massbank prefixes directly from Massbank GitHub repos.
=> Unique URLs field and Massbank prefixes loading from GitHub

R/BiodbConn.R, R/BiodbDbsInfo.R, R/BiodbEntry.R, R/BiodbFactory.R, R/BiodbRequestScheduler.R, R/ChebiConn.R, R/ChemspiderConn.R, R/ExpasyEnzymeConn.R, R/HmdbMetabolitesConn.R, R/HmdbMetabolitesEntry.R, R/KeggCompoundConn.R, R/KeggConn.R, R/LipidmapsStructureConn.R, R/MassCsvFileConn.R, R/MassbankConn.R, R/MirbaseMatureConn.R, R/NcbiEntrezConn.R, R/NcbiGeneConn.R, R/NcbiPubchemConn.R, R/PeakforestCompoundConn.R, R/PeakforestConn.R, R/PeakforestMassConn.R, R/RemotedbConn.R, R/UniprotConn.R, README.md, man/BiodbDbsInfo-class.Rd, man/BiodbRequestScheduler-class.Rd, man/ChemspiderConn-class.Rd, vignettes/database-extraction.Rmd
Remove getBaseUrl().
Remove getUrl().
=> Remove some deprecated methods.

README.md, tests/res/entry-ncbi.pubchem.comp-65124.json, tests/res/offline-cache/ncbi.pubchem.comp-65124.xml
=> Update NCBI PubChem Comp ref test files.

.Rbuildignore, Makefile, R/MassCsvFileConn.R, man/Biodb-class.Rd, man/BiodbConn-class.Rd, man/BiodbEntry-class.Rd, man/ChemspiderConn-class.Rd, man/ExpasyEnzymeConn-class.Rd, man/KeggConn-class.Rd, man/MassSqliteConn-class.Rd, man/MassdbConn-class.Rd, man/UniprotConn-class.Rd, tests/testthat.R
=> Enable testthat tests in R check.

R/KeggPathwayConn.R, tests/testthat/db-kegg.pathway-tests.R
When called with unknown compound.
=> Correct getDecoratedGraphPicture().

R/KeggCompoundConn.R, R/KeggEntry.R, R/KeggModuleEntry.R, R/KeggPathwayEntry.R, tests/testthat/db-kegg.compound-tests.R
=> Hotfix get pathway ids

Makefile, R/KeggCompoundConn.R, R/KeggPathwayConn.R, tests/testthat/db-kegg.compound-tests.R
=> Now retrieve pathways listed directly in compound.

R/BiodbConn.R, R/BiodbEntry.R, R/KeggCompoundConn.R, R/KeggEnzymeConn.R, R/KeggModuleEntry.R, R/KeggPathwayConn.R, R/KeggPathwayEntry.R, tests/testthat/db-kegg.enzyme-tests.R
=> Correct pathways found from enzyme in KEGG.

.travis.yml, Makefile, R/Biodb.R, R/BiodbConfig.R, R/BiodbConnBase.R, R/BiodbDbInfo.R, R/BiodbDbsInfo.R, R/BiodbFactory.R, R/BiodbObject.R, R/MirbaseConn.R, R/MirbaseMatureConn.R, README.md, inst/definitions.yml, man/MirbaseMatureConn-class.Rd, tests/testthat.R, tests/testthat/common.R, tests/testthat/db-mirbase.mature-tests.R, tests/testthat/engine-10-object-printing-tests.R
=> Db disabling

R/BiodbConfig.R, R/BiodbInfoReporter.R, R/BiodbObserver.R, R/KeggPathwayConn.R, tests/testthat/db-kegg.pathway-tests.R
=> Test keggpathway extractshapes

R/BiodbConn.R, R/MassSqliteConn.R, R/generic_tests.R
=> Rename some fct with "volatile" qualifier.

vignettes/new_connector.Rmd, vignettes/new_entry_field.Rmd
=> Start reviewing new connector vignette.

.travis.yml, R/BiodbPersitentCache.R, tests/testthat/test_120_mass.csv.file.R, tests/testthat/test_130_mass.sqlite.R, tests/testthat/test_300_persistent_cache.R
=> Improve persistent cache info

R/BiodbPersitentCache.R, README.md
=> Create parent of cache folder if needed for migration.
